# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo log in to Amazon ECR...
#       - aws --version
#       - echo $AWS_DEFAULT_REGION
#       # - $(aws ecr get-login-password --region us-east-1)
#       # - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 266583958309.dkr.ecr.us-east-1.amazonaws.com/aws-ecs-docker
#       - aws ecr get-login-password --region sa-east-1
#       - REPOSITORY_URI=266583958309.dkr.ecr.sa-east-1.amazonaws.com/arara-frota-emissao
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_TAG=${COMMIT_HASH:=latest}
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image.
#       - docker build -t $REPOSITORY_URI:latest .
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - docker push $REPOSITORY_URI:latest
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
#       - echo write definitions file...
#       - printf '[{"name":"exp-code-pipeline","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
# artifacts:
#   files: imagedefinitions.json


version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 266583958309.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...      
      - docker build -t arara-frota-emissao .
      - docker tag arara-frota-emissao:latest 266583958309.dkr.ecr.sa-east-1.amazonaws.com/arara-frota-emissao:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 266583958309.dkr.ecr.sa-east-1.amazonaws.com/arara-frota-emissao